spring:
  application:
    name: mall-search
  profiles:
    active: dev #默认为开发环境
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    password: foobared123
    url: redis://foobared123@127.0.0.1:6379
    lettuce:
      pool:
        max-wait: -1
        min-idle: 5
        max-idle: 10
server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml



